import { z } from 'zod';
import { AssetStatus } from '@prisma/client';

export const createAssetSchema = z.object({
  name: z.string().min(1, 'Name is required').max(200),
  categoryId: z.string().uuid('Invalid Category ID'),
  assetCode: z.string().optional(), // generated by service if not provided
  description: z.string().optional(),
  departmentId: z.string().uuid('Invalid Department ID').optional(),
  locationId: z.string().uuid('Invalid Location ID').optional(),
  status: z.nativeEnum(AssetStatus).default(AssetStatus.available),
  serialNumber: z.string().optional(),
  assetModel: z.string().optional(),
  manufacturer: z.string().optional(),
  purchaseDate: z.coerce.date().optional(),
  purchaseCost: z.number().nonnegative('Cost cannot be negative').optional(),
  warrantyExpiryDate: z.coerce.date().optional(),
  expectedLifeYears: z.number().int().positive('Life years must be positive').optional(),
  customFields: z.record(z.any()).default({}),
  notes: z.string().optional(),
});

export const updateAssetSchema = z.object({
  name: z.string().min(1, 'Name cannot be empty').max(200).optional(),
  categoryId: z.string().uuid('Invalid Category ID').optional(),
  description: z.string().optional(),
  departmentId: z.string().uuid('Invalid Department ID').nullable().optional(),
  locationId: z.string().uuid('Invalid Location ID').nullable().optional(),
  status: z.nativeEnum(AssetStatus).optional(),
  serialNumber: z.string().optional(),
  assetModel: z.string().optional(),
  manufacturer: z.string().optional(),
  purchaseDate: z.coerce.date().optional(),
  purchaseCost: z.number().nonnegative('Cost cannot be negative').optional(),
  warrantyExpiryDate: z.coerce.date().optional(),
  expectedLifeYears: z.number().int().positive('Life years must be positive').optional(),
  customFields: z.record(z.any()).optional(),
  notes: z.string().optional(),
});
